### ISSUE TITLE
Errors when uploading files using apollo-upload-client

### ISSUE THREAD

**Issue by maiguangyang** [nautilus/gateway#103]
Errors when uploading files using apollo-upload-client

apollo-upload-client uses formData to upload files and reports errors:
```
encountered error parsing body: invalid character '-' in numeric literal
```

**Comment by AlecAivazis** [comment]
hey @maiguangyang! Sorry you are running into this. I haven't yet tested the gateway with `apollo-upload-client` so i'm not totally surprised. If you want to dig into fixing this, let me know. I'm available on the gopher slack. Otherwise, I can try to find some time to handle it.

**Comment by obukhov** [comment]
Hi! I was looking into the issue and implemented part of the solution.

This is still work in progress but already works at least for the single file uploads.

@AlecAivazis if you have time please have a look and tell me what you think here (I will create a PR when it will be fully tested and fixed).

Here are the branches I am working at:
- https://github.com/nautilus/graphql/compare/master...obukhov:multipart-support
- https://github.com/nautilus/gateway/compare/master...obukhov:support-file-upload

**Comment by obukhov** [comment]
Shall this now be closed? @AlecAivazis :)

**Comment by AlecAivazis** [comment]
Yes, i think its safe to close this now - thanks again for your hard work @obukhov!
