### ISSUE TITLE
# github.com/carted/graphql/language/printer ..\..\..\github.com\carted\graphql\language\printer\printer.go:372:9: undefined: ast.NullValue

### ISSUE THREAD

**Issue by SupratickDey** [nautilus/gateway#104]
NullValue field is undefined.

**Comment by AlecAivazis** [comment]
Hey @SupratickDey - thanks for opening this issue.

Would you mind giving me a little more information? What script are you trying to run that is causing this error?

**Comment by SupratickDey** [comment]
Thanks for getting back to me, issue got resolved,  it exist  if we have
more than 1 version in our machine.

**Comment by AlecAivazis** [comment]
Ah np! Happy to hear it was fixed. Let me know if you run into more issues!
