### ISSUE TITLE
Merging types with different set of interfaces 

### ISSUE THREAD

**Issue by berend** [nautilus/gateway#117]
We stumbled upon another thing. 

When we combine a type via two schemas and in one schema that type implements another interface (`Meta` in the example below):

A
```graphql
schema {
    query: Query
}

type Query {
    node(id: ID!): Node
    Thing(id: ID!): Thing
}


interface Node {
    id: ID!
}


type Thing implements Node {
    id: ID!
    foo: String!
}
```

B

```graphql
schema {
    query: Query
}

type Query {
    node(id: ID!): Node
    Thing(id: ID!): Thing
}


interface Node {
    id: ID!
}

type Thing implements Meta, Node {
    id: ID!
    bar: String!
    created_at: String!
}

interface Meta {
    created_at: String!
}
```

We then get an error on `gateways.New`:

```
object type does not implement a consistent set of interfaces. object types have different number of entries
```

We consider types that have a different amount of interfaces a valid use case. And if we comment out https://github.com/nautilus/gateway/blob/38e5c1ae9a4e4af598f359e3de1aab93c8fea62d/merge.go#L236-L237
everything still works, no error on startup, querying works.

So, question is why is that check in there?

**Comment by AlecAivazis** [comment]
hey again @berend! It's very likely that this is a mistake on my part. Iirc, I was concerned about interfaces spanning service boundaries and wanted to avoid any potential issues.  I think you are correct and that it can be removed in general.

**Comment by berend** [comment]
I'll do a PR for that.

Not sure if I can come up with tests for that. Maybe I can include that example from above somewhere? If you have a similar test, I would be thankful for pointing to it.

**Comment by berend** [comment]
Having a better overview now!

There is a test for said check here 

https://github.com/esome/gateway/blob/07174ffa3475f3a57d6c63f9e1269d936e2ca77e/merge_test.go#L268-L284

I am going to remove that one from the test table and do a different one that makes this clear.

I found another bug, will handle that in the next PR.
