### ISSUE TITLE
Customize log format

### ISSUE THREAD

**Issue by kirill-amboss** [nautilus/gateway#122]
Hi there,

It seems that there's no way to change the gateway's log format, except for hardcoding the desired format In `logging.go`.

Are there any plans to fix this, or are you open to a contribution fixing this?

I was thinking about proposing a PR that would extract a logger interface and adding the `withLogger` option to the `gateway` config but wasn't sure if it was the best way to solve the issue.

Any comments on this?

Thanks.

**Comment by AlecAivazis** [comment]
Hey @kirill-amboss!

Thanks for being patient while I found some time to look over your contribution.
