### ISSUE TITLE
Conflicts with the internal schema

### ISSUE THREAD

**Issue by flovilmart** [nautilus/gateway#143]
Hi, thanks for this getting this tool out!

We're exploring using this project and when I hook up upstream graphQL servers backed by [graphql-relay-js](https://github.com/graphql/graphql-relay-js/), we get field / interface definition conflicts.
 
By default, the relay-js project [includes descriptions](https://github.com/graphql/graphql-relay-js/blob/main/src/node/node.js#L36-L76) describing node.

It seems fragile to crash the server if an upstream had a conflicting description on the `node` or `ID!` description, as those are pretty much standard and hidden from the end user.

I'd be happy to provide a PR for resolving this issue.

**Comment by AlecAivazis** [comment]
Ah yea I agree that a different description probably shouldn't cause this kind of error. Please feel free to open a PR addressing this.

**Comment by flovilmart** [comment]
Perfect! What do you prefer as a resolution? Skip the description? Merge them?

**Comment by AlecAivazis** [comment]
Hm, good question. I'm really not sure what the right move is. How about, if one of the descriptions is empty and another one isn't, lets use the non-empty value. If the content is actually different, let's arbitrarily choose the first one

**Comment by flovilmart** [comment]
Good idea! Let me see what I can do. I assume this logic should apply to any description (enums, fields, interfaces etc).
Let me see what I can do for that!

**Comment by JohnStarich** [comment]
@flovilmart Should be fixed! You can try it out in version `v0.2.3`

**Comment by flovilmart** [comment]
wonderful! Thanks!
