### ISSUE TITLE
 How to run the gateway and the sub services on a single port ?

### ISSUE THREAD

**Issue by gedw99** [nautilus/gateway#150]
Thanks for makin this. It's really clean if you know what i mean.

At the moment the code wants to run with each service on a different port.

For certain deployments i want to be able to run the gateway and the sub services on a single port ( for example on a desktop or mobile device ), and for scaled out scenarios with each on their own ports ( for example on many servers ).

Can you think of an approach to do this that is minimal and clean ?

**Comment by AlecAivazis** [comment]
Hey @gedw99! Appreciate the kind words.

If I'm following you correctly, I think you might be able to pull off what you want by using defining in-memory `Queryer` that executes your schema from the same process as the gateway. [Here](https://gateway.nautilus.dev/advanced/batching) is an example of what that could look like. 

Let me know if that works for you! I appreciate your patience - took me longer than I hoped to get this reply out

**Comment by AlecAivazis** [comment]
Going to close this since its gone a bit stale. @gedw99 let me know if you still need guidance
