### ISSUE TITLE
Persisted Query doesn't work correctly with Apollo Client & There is no way to use another cache mechanism like Memcache or Redis

### ISSUE THREAD

**Issue by ozanturhan** [nautilus/gateway#156]
Hi,

I am trying to use nautilus gateway with apollo automatic persisted queries. Apollo gateway returns PersistedQueryNotFound error with http status 200. But nautilus gateway return it with 400. When I change http status from 400 to 200 thats work properly.

```go
if err != nil {
	response, err := json.Marshal(formatErrorsWithCode(nil, err, "GRAPHQL_VALIDATION_FAILED"))
	if err != nil {
		// if we couldn't serialize the response then we're in internal error territory
		response, err = json.Marshal(formatErrors(nil, err))
		if err != nil {
			response, _ = json.Marshal(formatErrors(nil, err))
		}
	}

        // if error response contain PersistedQueryNotFound return 200
	if strings.Contains(string(response), MessageMissingCachedQuery) {
		emitResponse(w, http.StatusOK, string(response))
		return
	}

	emitResponse(w, http.StatusBadRequest, string(response))
	return
}
```

I am using apollo-link-persisted-queries in client side.
```js
import { createPersistedQueryLink } from 'apollo-link-persisted-queries';

...

const links = ApolloLink.from([createPersistedQueryLink(), errorLink, httpLink]);

return new ApolloClient({
  link: links,
  cache,
});
```

Another thing I realized after apq working correctly, nautilus adds  persisted query hash to all responses. I think It should be added once. Thats not a big problem but Apollo adds it only once. 

And also I would like to use memcache instead of in memeory cache for apq's like Apollo

```js
const server = new ApolloServer({
  typeDefs,
  resolvers,
  persistedQueries: {
    cache: new MemcachedCache(
      ['memcached-1.local', 'memcached-2.local', 'memcached-3.local'],
      { retries: 10, retry: 10000 }, // Options
    ),
  },
});
``` 

I tried to add memcache for Nautilus and I did. But I faced an issue. Because currently Nautilus caches  QueryPlanCacheItem and I can't unmarshall this struct. I looked Apollo memcached and I realized Apollo caches query string not whole plan.

Can you check this commit https://github.com/ozanturhan/gateway/commit/367ba154bc5adc2a2c1ce823e8b9be319a7bf076 ? It adds memcache support but I haven't created pull request yet. I would like to solve this problem but maybe my implementation is not good for your package. Would you like to mplement something like that?

Usage With Memcache
```go
gateway.New(schemas, gateway.WithQueryPlanCache(gateway.NewAutomaticQueryPlanCache(gateway.NewMemcachedCache("127.0.0.1:11211"))))
```

Usage With InMemoryCache
```go
gateway.New(schemas, gateway.WithQueryPlanCache(gateway.NewAutomaticQueryPlanCache(gateway.NewInMemoryCache())))
```

**Comment by AlecAivazis** [comment]
Hey @ozanturhan - sorry it took so long to reply! If apollo returns a 200 when doing APQ, nautilus should do the same. If you have time to submit a PR with that change I will gladly accept it. In regards to memcache, I don't I'd like to assume that memcache is available for the default query plan cache but if you wanted to pull your changes into a third party repository, i would love to link to it in the docs so people can take advantage of what you put together

**Comment by JohnStarich** [comment]
➕ to Alec's comment.

@ozanturhan If I understand the problem correctly, the bad request error appears to be an Apollo server-side issue, rather than a gateway one.

Regarding caches: You can make use of the [`QueryPlanCache` interface](https://pkg.go.dev/github.com/nautilus/gateway#QueryPlanCache) to implement and swap in your own cache.
We'd be happy to link to a memcached QueryPlanCache implementation if one is published. I think for the purposes of the gateway library, it's probably best to keep things simple while also allowing swappable caches.

I'll go ahead and close since it appears to be an issue on that Apollo server's side. Feel free to continue discussion here as needed.
