### ISSUE TITLE
-bash: ./gateway: No such file or directory

### ISSUE THREAD

**Issue by ivekov** [nautilus/gateway#157]
After downloading the files of service, i run:
' ./gateway start --port 4000 --services http://localhost:3000,http://localhost:3001'

And recieve the error:
'-bash: ./gateway: No such file or directory'

Tried different installation variants.

**Comment by ivekov** [comment]
You have to change guide, or tell everyone to:

1. Install golang
2. Go to cmd/gateway
3. Run 'go build .'
4. Run 'go run . start --port 4000 --services http://localhost:3000,http://localhost:3001 '

Otherwise it won't start. I work with node, php, python, how could i knew that i have to use 'go build' command?

**Comment by JohnStarich** [comment]
@ivekov Thanks for opening. This is fixed as of [v0.2.5](https://github.com/nautilus/gateway/releases/tag/v0.2.5)
