### ISSUE TITLE
Custom config in GraphQL Playground

### ISSUE THREAD

**Issue by ashwin153** [nautilus/gateway#158]
Currently, it is not possible to pass in config to the GraphQL Playground.

https://github.com/nautilus/gateway/blob/5d984b36965ab4c5a1903388ffcb1d58277f56cf/graphiql.go#L493

However, I would like to be able to customize things like settings (e.g., set `"request.credentials": include`). Would it be possible to allow users to inject configuration when creating the GraphQL Playground?

**Comment by JohnStarich** [comment]
Thanks for opening @ashwin153! This was added in `v0.2.8`
