### ISSUE TITLE
about cors settings

### ISSUE THREAD

**Issue by codebdy** [nautilus/gateway#194]
Hi, Dears
i meet cors problem，when client seent "OPTION" requet, get 405 error, I find the source not not process "OPTION" method ：
![image](https://github.com/nautilus/gateway/assets/18096128/9858023b-660f-4a0a-84de-40e6bbeb82bd)

Is any way to fixed it？

**Comment by codebdy** [comment]
add this code, fixed:
![image](https://github.com/nautilus/gateway/assets/18096128/0c067a6c-c440-4235-9b3d-9d7a90f3c0f8)

is right?

**Comment by JohnStarich** [comment]
I think your solution is a good one.

It's unclear to me how a GraphQL server should respond to an `OPTIONS` request. I skimmed the draft specification for [GraphQL over HTTP](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md) and I only see `POST` and `GET` mentioned.

I think handling CORS requests in your own middleware wrapped around the gateway is probably the best choice for now. Perhaps if there's some precedent or clarification in the spec, then we could support `OPTIONS` in gateway natively.

**Comment by JohnStarich** [comment]
You could adopt a similar HTTP handler for `OPTIONS` to the one provided in `cmd/gateway` here: https://github.com/nautilus/gateway/blob/3c19e01d118981add189ca7abe5e56a784918455/cmd/gateway/http.go#L48-L59

The library though may need to wait to adopt this until the GraphQL community establishes the right path forward. I'd be happy to reopen this once that becomes clearer.
