### ISSUE TITLE
Wrong type for variable values containing object

### ISSUE THREAD

**Issue by jakubknejzlik** [nautilus/gateway#68]
During testing the gateway I've probably found bug when using variables with object (scalar values work fine).

## Setup
I have existing api exposed at https://graphql-orm-example.herokuapp.com/graphql and running gateway (v0.0.9) locally by running:
```
./gateway start --port 8080 --services https://graphql-orm-example.herokuapp.com/graphql
```

## Inputs
Query:
```
query($filter:TaskFilterType) {
  tasks(filter:$filter) {
    items {
      id
      title
    }
  }
}
```
Variables
```
{
  "filter":{
    "assignee":{
      "id":"anything"
    }
  }
}
```

## Expected result
Current API returns empty list:
```{
  "data": {
    "tasks": {
      "items": []
    }
  }
}```

## Actual result
```{
  "data": {},
  "errors": [
    {
      "extensions": {
        "code": ""
      },
      "message": "Variable \"$filter\" of type \"ID!\" used in position expecting type \"TaskFilterType\"."
    }
  ]
}
```

FYI: when providing the variables directly (without variables), it works fine, eg:

```
query {
  tasks(filter:{
    assignee:{
      tasks:{
        id:"aa"
      }
    }
  }) {
    items {
      id
      title
    }
  }
}```

**Comment by AlecAivazis** [comment]
Oh no! I'm sorry to hear this.

I'll try to get something fixed ASAP. Do other non-object variables get threaded through correctly? I should have a test somewhere that verifies this works but maybe I missed objects

**Comment by AlecAivazis** [comment]
*sigh* sorry about the spam didn't want to mark the issue as closed until you verified. This should now be fixed in the latest version.

Sorry again for the inconvenience!

**Comment by jakubknejzlik** [comment]
Wow, thanks for quick reply! I’ll test it in few hours and let you know :)

**Comment by jakubknejzlik** [comment]
It did help, but also helped me to discover another one with arrays.
Plain query works (same setup):
```
query {
  tasks(sort:[TITLE_ASC]) {
    items {
      id
      title
    }
  }
}
```

but with variables:
```
query($sort:[TaskSortType!]) {
  tasks(sort:$sort) {
    items {
      id
      title
    }
  }
}
vars: {"sort":["TITLE_ASC"]}
```

Result:
```
{
  "data": {},
  "errors": [
    {
      "extensions": {
        "code": ""
      },
      "message": "Variable \"$sort\" of type \"ID!\" used in position expecting type \"[TaskSortType!]\"."
    }
  ]
}
```

**Comment by jakubknejzlik** [comment]
It did help, but also helped me to discover another one with arrays.
Plain query works (same setup):
```
query {
  tasks(sort:[TITLE_ASC]) {
    items {
      id
      title
    }
  }
}
```

but with variables:
```
query($sort:[TaskSortType!]) {
  tasks(sort:$sort) {
    items {
      id
      title
    }
  }
}
vars: {"sort":["TITLE_ASC"]}
```

Result:
```
{
  "data": {},
  "errors": [
    {
      "extensions": {
        "code": ""
      },
      "message": "Variable \"$sort\" of type \"TaskSortType!\" used in position expecting type \"[TaskSortType!]\"."
    }
  ]
}
```

**Comment by AlecAivazis** [comment]
Alright cool I suspect that's a bug in the same place. I'll take a look soon

**Comment by AlecAivazis** [comment]
This should be fixed in this PR: https://github.com/nautilus/gateway/pull/69

Decided this was better than merging straight to master so we can verify before shooting the gateway version up

**Comment by jakubknejzlik** [comment]
Getting closer and closer :D ... tried on nautilus/graphql v0.0.5 and got this:
```
{
  "data": {},
  "errors": [
    {
      "extensions": {
        "code": ""
      },
      "message": "Variable \"$sort\" of type \"[TaskSortType]\" used in position expecting type \"[TaskSortType!]\"."
    }
  ]
}
```

**Comment by AlecAivazis** [comment]
Okay try again with `v0.0.6`

**Comment by jakubknejzlik** [comment]
I'm stuck a little bit on #70 , but from playground it seems ok.

**Comment by AlecAivazis** [comment]
Awesome - Ill take a look at that issue now. Are you able to send all of your filters now?

**Comment by jakubknejzlik** [comment]
Yep, I'll test it on our main API and deploy it to other projects (if everything's ok, it goes to production (small project) in few days :) ). I'll reopen this one or create new issue if I found anything 👍
