### ISSUE TITLE
Content-type header set to text/plain

### ISSUE THREAD

**Issue by jakubknejzlik** [nautilus/gateway#70]
Currently the GraphQL server returns `Content-Type: text/plain` although it's returning json. I'm not sure if it's in the specs, but most of the servers return `application/json`.

I'm currently "hacking" it by custom handler func:
```
http.HandleFunc("/graphql", func(res http.ResponseWriter, req *http.Request) {
	res.Header().Set("Content-Type", "application/json")
	gw.PlaygroundHandler(res, req)
})
```
(https://github.com/graphql-services/graphql-gateway/blob/feature/nautilus-gateway/main.go#L67). Seems to work fine, but it would be nice if the server returns `application/json` by default.

**Comment by jakubknejzlik** [comment]
The main reasons for this are:
# the original gateway(s) return also `application/json`
# it messes up with the client library which is expecting json

But the playground is working fine (not sure about official apollo client library). Feel free to correct me and close this if `plain/text` is also valid content type for GraphQL server response :)

**Comment by AlecAivazis** [comment]
You are correct! the Content-Type should be `application/json`. There is now a PR open to fix this 😄

**Comment by AlecAivazis** [comment]
This should now be fixed in `v0.0.12`

**Comment by jakubknejzlik** [comment]
Tested and working 👏 🙇

**Comment by AlecAivazis** [comment]
Awesome! Let me know if you run into any problems. Afaik, you are one of the first people to try this in the wild so there might be more issues 🙈
