### ISSUE TITLE
Memory leak (possibly)

### ISSUE THREAD

**Issue by jakubknejzlik** [nautilus/gateway#75]
Running gateway consumes more and more memory over time. I'm not sure if this is caused by memory leak, but after startup it has ~5MB allocated and after few days with small usage (10req/minute) it slowly gets to ~200MB and rising. We have memory limit to 256MB so it get's restarted automatically (k8s). Approximately 4x in last 3 days.

Any idea what could be causing the problem or how to debug this?

**Comment by AlecAivazis** [comment]
Oh no! 😱 

Thanks for noticing this. I will see if I can hunt it down. That being said, can you give me whatever information you can about the schema, queries being fired, etc. There is a lot of goroutine orchestration in the gateway so it's possible something is leaking.

**Comment by AlecAivazis** [comment]
This page seems to have a good description on using `pprof` to hunt down goroutine leaks: https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/

I'm going to try to reproduce this leak locally with a test service. Will keep this issue up to date wiht my findings

**Comment by AlecAivazis** [comment]
@jakubknejzlik is this gateway querying the service that you were using before? I'd like to find the culprit behind this leak asap

**Comment by jakubknejzlik** [comment]
@AlecAivazis sorry for the delay....busy weeks :) . Actually I'm able to reproduce locally.

Current sources:
https://github.com/graphql-services/graphql-gateway/blob/feature/nautilus-gateway/main.go

Command:
```
GRAPHQL_URL=https://graphql-orm-example.herokuapp.com/graphql go run main.go
```

Curl in cycles to make some load:

### Introspection query:
```
for n in {1..100}; do curl 'http://localhost/graphql' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Origin: http://localhost' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,cs;q=0.8,sk;q=0.7' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36' -H 'content-type: application/json' -H 'accept: */*' -H 'Referer: http://localhost/graphql' -H 'X-Apollo-Tracing: 1' -H 'Connection: keep-alive' --data-binary '{"operationName":"IntrospectionQuery","variables":{},"query":"query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n"}' --compressed; done
```
Memory usage:
after startup: 9.2MB
after 100 queries: 16.3MB
after 200 queries: 23.7MB
after 300 queries: 29.5MB
after 400 queries: 35.7MB
after 500 queries: 43.3MB
after 600 queries: 49.3MB
after 700 queries: 56.1MB
after 1700 queries: 119.6MB

### Data loading query (not that steep, but still rising):
```
for n in {1..100}; do curl 'http://localhost/graphql' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Origin: http://localhost' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,cs;q=0.8,sk;q=0.7' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36' -H 'content-type: application/json' -H 'accept: */*' -H 'Referer: http://localhost/graphql' -H 'Connection: keep-alive' --data-binary '{"operationName":null,"variables":{},"query":"{\n  companies {\n    items {\n      id\n      name\n      employees {\n        id\n        email\n        firstName\n        lastName\n      }\n    }\n    count\n  }\n}\n"}' --compressed; done
```
after startup: 9.2MB
after 100 queries: 10.6MB
after 200 queries: 11.4MB
after 300 queries: 12.2MB
after 400 queries: 13.6MB
after 1400 queries: 31.1MB

I left it running for few minutes, but the memory consumption keeps same.

This is the latest logs with GODEBUG=gctrace=1 :
```
gc 107 @103.911s 0%: 0.012+4.1+0.019 ms clock, 0.051+0.79/4.0/9.9+0.076 ms cpu, 9->9->5 MB, 10 MB goal, 4 P
gc 108 @105.463s 0%: 0.007+4.0+0.003 ms clock, 0.031+0.61/3.9/9.4+0.015 ms cpu, 9->10->5 MB, 10 MB goal, 4 P
gc 109 @107.178s 0%: 0.005+4.6+0.003 ms clock, 0.021+0.63/4.5/9.5+0.014 ms cpu, 10->10->5 MB, 11 MB goal, 4 P
WARNING Network Error: Post https://graphql-orm-example.herokuapp.com/graphql: context canceled 
GC forced
gc 29 @121.974s 0%: 0.074+8.8+0.005 ms clock, 0.29+0/8.8/21+0.023 ms cpu, 3->3->2 MB, 4 MB goal, 4 P
scvg0: inuse: 9, idle: 50, sys: 60, released: 0, consumed: 60 (MB)
```

**Comment by edwinmo-splunk** [comment]
@AlecAivazis and I had chatted that my team was going to conduct some performance tests and would also spend some time reproducing the memory leak. I'm back with some results that corroborates the memory leak issue.

Test environment: K8s pod with 1Gi memory and 2 cpu. 
Test scenario: K8s cron job that executes every minute. It queries the graphql service running Nautilus (and routing an external GraphQL service through the NetworkQueryer) 60 times at each invocation for a very rough estimate of ~60 requests per minute, or ~1 rps.

![image](https://user-images.githubusercontent.com/19786913/70282078-a37f6580-1771-11ea-95c9-7c866e742dcb.png)

Each datapoint is at 30 second intervals. I didn't run the test until we went OOM, but a trend can be observed of ~0.468MiB/30s at ~1rps traffic.

We have plans to analyze a possible fix for this issue for the next 2 weeks and might need some help navigating the codebase @AlecAivazis. Please let me know if you have any ideas on where to start!

**Comment by AlecAivazis** [comment]
Oh damn! I'm sorry to see that but at least we are confident there is a problem. Thank you so much for going through the effort to generate these charts.

Both of the the planning and execution phases involve a lot parallelism and could be the culprit. You should be able to isolate each phase by replacing the intsance with the ones I use in tests. I will pokea round a bit and see if anything stands out

**Comment by AlecAivazis** [comment]
This is now fixed thanks to the awesome work by @bk-splunk - thanks again!
