### ISSUE TITLE
github.com/vektah/gqlparser package path is updated to v2, an error is reported

### ISSUE THREAD

**Issue by maiguangyang** [nautilus/gateway#86]
github.com/vektah/gqlparser package path is updated to v2, an error is reported

Reason: github.com/vektah/gqlparser The package name has been modified, which causes the project to run incorrectly

**Comment by AlecAivazis** [comment]
hey @maiguangyang - thanks for letting me know about this.

I spent some time updating all of the references this morning but something is causing one of the tests to fail. I will try to pick this back up tonight and get a fix out asap.

**Comment by AlecAivazis** [comment]
Sorry this took so long! Better late than never, right?

Thanks again for bringing this to my attention
